[phases.setup]
nixPkgs = ['nodejs_20']
nixOverlays = []
nixLibs = []

[phases.install]
cmds = [
  'cp -r shared rest-api/ || echo "shared directory copied"',
  'cd rest-api && npm install --no-cache --no-optional --omit=dev'
]

[phases.build]
cmds = [
  'cd rest-api && npm run build',
  'ls -la rest-api/dist || echo "dist not found"'
]

[start]
cmd = 'NODE_ENV=production node rest-api/dist/index.js'

[variables]
NPM_CONFIG_CACHE = '/tmp/.npm'
NPM_CONFIG_UPDATE_NOTIFIER = 'false'

