[phases.setup]
nixPkgs = ['nodejs_20']

[phases.install]
cmds = ['npm install --no-cache --no-optional --omit=dev']

[phases.build]
cmds = ['npm run build']

[start]
cmd = 'npm start'

[variables]
NPM_CONFIG_CACHE = '/tmp/.npm'
NPM_CONFIG_UPDATE_NOTIFIER = 'false'