[phases.setup]
nixPkgs = ['nodejs_20']

[phases.install]
# Copy shared directory and install dependencies
cmds = [
  'cp -r ../shared . || echo "shared already exists"',
  'npm install --no-cache --no-optional --omit=dev'
]

[phases.build]
# Build TypeScript
cmds = ['npm run build']

[start]
cmd = 'npm start'

[variables]
NPM_CONFIG_CACHE = '/tmp/.npm'
NPM_CONFIG_UPDATE_NOTIFIER = 'false'